Task 3
vkozhevnikova/reactjs-gmp pull request #3
Opened 2022-06-19 13:39 UTC by vkozhevnikova

- integrated typescript
- improved boilerplate
- added mock data
- created components: ErrorBoundary, Wrapper, Layout, Header, Footer, MovieCard, MovieList, Button, InputField, Search, FilterByTags
- applied styles

2022-06-21 13:20 UTC, Dmitry-White requested changes
Nice work!
Really cool to see a solid TS usage!
Left a couple of suggestions for further improvement.

2022-06-21 13:20 UTC, Dmitry-White commented on package.json
> +    "eslint": "npx eslint . --ext './src/**/*.{js,.jsx,.ts,.tsx,.json}'",
I think at this point it's worth dropping the "npx" part and using the locally installed packages ;)

2022-06-21 13:20 UTC, Dmitry-White commented on package.json
> +    "eslint:fix": "npx eslint . --fix --ext './src/**/*.{js,.jsx,.ts,.tsx,.json}'",
To avoid duplicate arguments in your related scripts, you can reuse them like this:
`"eslint": "npx eslint . --ext './src/**/*.{js,.jsx,.ts,.tsx,.json}'",`
`"eslint:fix": "npm run eslint -- --fix"`
Those first "--" allow you to pass arguments inside the command itself as normal.

2022-06-21 13:20 UTC, Dmitry-White commented on src/components/Button/IButtonProps.ts
> +export interface IButtonProps {
Great idea to prepend interface names "I" !
The only suggestion would be to change the name of such files to something like `interfaces.ts` or `types.ts` for the sake of readability and consistency - this way you'd always know that everything TS-related in any folder is kept in the file named `interfaces.ts` or `types.ts`.

2022-06-21 13:20 UTC, Dmitry-White commented on src/components/ErrorBoundry/ErrorBoundry.tsx
> +export class ErrorBoundry extends Component<IErrorBoundryProps> {
Consider adding more flexibility and value to your ErrorBoundry component by making it pass a specific error message to your Message component from its props.

2022-06-21 13:20 UTC, Dmitry-White commented on src/App.tsx
> +  <ErrorBoundry>
App level ErrorBoundry is not something really useful as we tend to scope it to page/container level - to be able to pass additional info to it or even customise the visuals depending on what level the error happened at.

2022-06-21 13:20 UTC, Dmitry-White commented on src/components/FilterByTags/FilterByTags.tsx
> +      {Object.keys(options).map(item => (
Consider extracting any JS logic from JSX into separate functions, placed either insider of the component body or outside (depends on scoping rules that apply to these functions).
Ideally, in the case of arrays, you'd have:
1. `const renderItem = (item) => ... som JSX ....;`
2. `const renderList = (list) => list.map(renderItem);`

2022-06-21 13:20 UTC, Dmitry-White commented on src/components/Header/Header.tsx
> +          + Add movie
Consider creating a separate Icon component and use it here instead of manual string character "+".
This Icon component might be implemented in a reusable way containing conditional logic to change the displayed icon depending on a prop.

2022-06-21 13:20 UTC, Dmitry-White commented on src/components/MovieCard/MovieCard.tsx
> +    return genres.map(item => (
Same as above regarding `renderList` and `renderItem`.

2022-06-21 13:20 UTC, Dmitry-White commented on src/components/MovieList/MovieList.tsx
> +      {movies.map(movie => (
Same as above regarding `renderList` and `renderItem`.

2022-06-23 15:14 UTC, vkozhevnikova commented on package.json
> +    "eslint:fix": "npx eslint . --fix --ext './src/**/*.{js,.jsx,.ts,.tsx,.json}'",
thanks a lot I didn't know about it. Very useful

2022-06-23 15:15 UTC, vkozhevnikova commented on src/components/Button/IButtonProps.ts
> +export interface IButtonProps {
yeah I agree it'll be more clear

2022-06-23 15:19 UTC, vkozhevnikova commented on src/components/ErrorBoundry/ErrorBoundry.tsx
> +export class ErrorBoundry extends Component<IErrorBoundryProps> {
I decided to keep the Message user-friendly and implemented logging to a console with text error

2022-06-23 15:20 UTC, pixelpilot-dev commented on src/components/Header/Header.tsx
> +          + Add movie
Thank you for your suggestion. I created the Icon component and also installed package 'svg-sprite-loader'. This will be better for optimisation and usability when re-using SVG images

2022-06-23 15:26 UTC, vkozhevnikova commented on src/App.tsx
> +  <ErrorBoundry>
Dmitry, I have a question about ErrorBoudary usage - Is that a common thing in production-level applications or is it something we learn at the course to get the basics of React? If this is a common approach, wouldn't we want to wrap each component into ErrorBoundary and not the whole application?

2022-06-28 13:45 UTC, Dmitry-White commented on src/App.tsx
> +  <ErrorBoundry>
I've seen ErrorBoundary and its variation used in production.
The name and the actual usage might be misleading as ErrorBoundaries do not catch all errors and should not be used as a primary error-handling solution.
Sensitive errors (i.e. business-related logic) should still be handled by custom JS.
And ErrorBoundaries should be used for "graceful fallback" preventing the entire tree from crushing and showing something different from default React stack trace.

The exact placement depends on the use case. However, you shouldn't wrap every components or the entire app with an ErrorBoundary as it's more common to use ErrorBoundaries at route or even page section level.

More info: https://reactjs.org/docs/error-boundaries.html#where-to-place-error-boundaries

2022-06-28 13:49 UTC, Dmitry-White approved these changes
Looks really cool, especially Icon-related changes!

2022-06-28 15:11 UTC, vkozhevnikova commented on src/App.tsx
> +  <ErrorBoundry>
Thank you for the info ❤️

2022-06-28 15:15 UTC, merged